#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'radarr'
        intport: '7878'
        extport: '7878'
        image: 'linuxserver/radarr:nightly'

    # CORE (MANDATORY) ############################################################
    - name: 'Including cron job'
      include_tasks: '/opt/coreapps/apps/_core.yml'

    - name: 'Including plugins'
      include_tasks: '/opt/coreapps/apps/_plugins.yml'

    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          traefik.docker.network: 'proxy'
          traefik.http.routers.radarr-secure.entrypoints: 'websecure'
          traefik.http.routers.radarr-secure.rule: 'Host(`{{ucname.stdout}}.{{domain.stdout}}`)'
          traefik.http.services.radarr.loadbalancer.server.port: '{{extport}}'

    - name: 'Setting {{pgrole}} Volumes'
      set_fact:
        pg_volumes:
          - '{{path.stdout}}:{{path.stdout}}'
          - '/opt/appdata/{{pgrole}}:/config'
          - '/opt/appdata/{{pgrole}}/mp4_automator:/config_mp4_automator'

    - name: 'Setting {{pgrole}} ENV'
      set_fact:
        pg_env:
          PUID: '1000'
          PGID: '1000'

    # MAIN DEPLOYMENT #############################################################

    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        published_ports:
          - '{{ports.stdout}}{{extport}}:{{intport}}'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
          - name: proxy
        state: started
        labels: '{{pg_labels}}'

    - name: 'Checking for existing app data'
      stat:
        path: /opt/appdata/{{pgrole}}/config.xml
      register: confcheck

    - name: 'Update {{pgrole}} for first time use'
      block:
        - pause:
            prompt: "Wait for {{pgrole}} start up"
            seconds: 5
